namespace McpEndpoints.Generator;

public static class Emitter
{
    public static string Emit(EndpointModel model)
    {
        return $$"""
            // <auto-generated/>
            #nullable enable
            namespace {{model.Namespace}}.Generated;

            [global::ModelContextProtocol.Server.McpServerToolType]
            public static class {{model.GeneratedClassName}}
            {
                [global::ModelContextProtocol.Server.McpServerTool(Name = "{{model.ToolName}}")]
                public static string Invoke() => "{{model.ToolName}}";
            }
            """;
    }
}
