using System.Linq;

namespace McpEndpoints.Generator;

public static class Emitter
{
    public static string Emit(EndpointModel model)
    {
        var genNs = string.IsNullOrEmpty(model.Namespace) ? "Generated" : model.Namespace + ".Generated";
        var desc = (model.Description ?? "").Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", " ").Replace("\n", " ");
        var paramComments = string.Join("\n", model.Parameters
            .Select(p => $"// param {p.Name} -> ParameterSource.{p.Source}"));
        return $$"""
            // <auto-generated/>
            #nullable enable
            namespace {{genNs}};

            // route: {{model.RouteTemplate}}
            // verb: "{{model.HttpMethod}}"
            // description: {{desc}}
            {{paramComments}}
            [global::ModelContextProtocol.Server.McpServerToolType]
            public static class {{model.GeneratedClassName}}
            {
                [global::ModelContextProtocol.Server.McpServerTool(Name = "{{model.ToolName}}")]
                [global::System.ComponentModel.Description("{{desc}}")]
                public static string Invoke() => "{{model.ToolName}}";
            }
            """;
    }
}
